# Generated by Django 4.0.4 on 2022-05-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeysValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KEY', models.CharField(max_length=255)),
                ('VALUE', models.JSONField()),
                ('unix_time', models.PositiveBigIntegerField()),
            ],
        ),
    ]
