# Generated by Django 4.0.4 on 2022-05-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterstore_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keysvalues',
            name='KEY',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
